# $Id: makefile,v 1.1.1.1 2007/07/27 20:37:37 mng Exp $
# ------------------------------------------------------

# Build files
sim_top= WiFiTest.bsv
dut_top= Transceiver.bsv
#dut_files = ZtideTop.bsv

MAINV= ${BLUESPECDIR}/Verilog/main.v

build: lib bsim ivsim

include ../bsv.mk
